# Generated by Django 5.1.3 on 2024-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='es_privado',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='torneo',
            name='max_jugadores',
        ),
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(default='Arnau', max_length=255),
        ),
    ]
