# Generated by Django 5.1.3 on 2024-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_remove_torneo_es_privado_remove_torneo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
