# Generated by Django 5.1.3 on 2024-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_alter_torneo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='es_privado',
            field=models.BooleanField(default=False),
        ),
    ]
