# Generated by Django 5.1 on 2024-12-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchhistory',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='player1',
            field=models.ForeignKey(db_column='player1_name', on_delete=django.db.models.deletion.CASCADE, related_name='match_as_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='player2',
            field=models.ForeignKey(db_column='player2_name', on_delete=django.db.models.deletion.CASCADE, related_name='match_as_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='winner',
            field=models.ForeignKey(db_column='winner_name', on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='matchhistory',
            table='users_matchhistory',
        ),
    ]
