# Generated by Django 5.1 on 2024-12-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_matchhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponguser',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='fortytwo_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='ponguser',
            table='users_ponguser',
        ),
    ]
